Repository JustforFun2112/WAGitHubGruppe11, pull requests merged in 2023-02, with the labels that each got.

#5 Aufgabe 3a Überarbeitung
  Aufgabe 3.R
Labels: documentation

#14 Update Aufgabe 3.R
  Aufgabe 3.R
Labels: bug

#20 Änderungen Aufgaben
  Datensatz_Aufgabe1
  WA.csv
  aufgabe-1-data-sim.R
Labels: documentation, help wanted
